server:
  port: 2222
spring:
  application:
    name: feign-service
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/